{% set name = "mistletoe-ebp" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ea7cb4f5ae7c12c3306be3bc917b093563c358b7291a1c787ab4c5e65b55766

build:
  number: 0
  entry_points:
    - mistletoe = mistletoe.cli.parse:main
    - mistletoe-bench = mistletoe.cli.benchmark:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - attrs >=19,<=20
    - pip
    - python >=3.6
  run:
    - attrs >=19,<=20
    - python >=3.6

test:
  imports:
    - mistletoe
  commands:
    - mistletoe --help

about:
  home: https://github.com/ExecutableBookProject/mistletoe-ebp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fast, extensible Markdown parser in pure Python.

extra:
  recipe-maintainers:
    - chrisjsewell
    - choldgraf
