{% set name = "mistletoe-ebp" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8278398271a5655516b90161b4dcf049c8ed5b699467336289564f80e5f8e86

build:
  number: 0
  entry_points:
    - mistletoe = mistletoe.__main__:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - attrs >=19,<=20
    - pip
    - python >=3.6
  run:
    - attrs >=19,<=20
    - python >=3.6

test:
  imports:
    - mistletoe
  commands:
    - mistletoe --help

about:
  home: https://github.com/ExecutableBookProject/mistletoe-ebp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fast, extensible Markdown parser in pure Python.

extra:
  recipe-maintainers:
    - chrisjsewell
    - choldgraf
